### ISSUE TITLE
Extra Frenzy button created that cannot be shut off.

### ISSUE THREAD

**Issue by Deadlander** [brunocalado/savage-pathfinder-enhanced#2]
Foundry v11.304
SWADE Core v3.0.4
Savage Pathfinder Enhanced v0.6.1
Better Rolls 2 v3.30

With the setting Better Rolls Global Actions active: When an Actor with Frenzy makes a melee attack roll, there are 2 Frenzy buttons active. You can shut the bottom button off, but the top one will not shut off when clicked. It instead toggles the bottom button.  See video below:

https://github.com/brunocalado/savage-pathfinder-enhanced/assets/13036735/cbe9e346-7a57-4b40-88dc-7de8158a05b1

**Comment by brunocalado** [comment]
fixed

What game is this? Savage Snows?
