### ISSUE TITLE
AA config for banish isn't working

### ISSUE THREAD

**Issue by Vogliadicone** [brunocalado/savage-pathfinder-enhanced#3]
After using your macro for Automated Animations the banish power didn't show an animation.

The macro set ip up like this:
![Banish_1](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/119852651/9dce2c29-3ec8-4580-8d9e-a019aa21578c)
But even after I set up the variant and color like this:
![Banish_2](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/119852651/88cda9ed-cddc-42bc-820e-8b7b48c42ba4)
nothing is happening, when I place the template over the tokens. Might be a problem of AA, but I wanted to let you know, that your config for this power isn't working.

- Foundry VTT: 11.305
- Swade System: 3.0.4
- Savage Pathfinder - Enhanced 0.6.2
- Automated Animations 4.2.60 (I configured AA to show the animation in general with the SWADE action roll)
- Sequencer 3.0.11
- SWADE Tools: 1.13.4
- Browser: Google Chrome

**Comment by Vogliadicone** [comment]
Just to let you know: I tested it again and it's working for single targets. Just when I'm using a template, the AA isn't showing up.

**Comment by brunocalado** [comment]
> using your macro for Automated Animations the banish power didn't show an anima

It's showing in here...

**Comment by Vogliadicone** [comment]
I first tested it only with templates and there it shows no effect. When targeting a single target, it works. But since I like the AA and 
 have no idea, how I can set it up for both, I'll stick with your set up.

**Comment by brunocalado** [comment]
> 

Ranged must have a target.
