### ISSUE TITLE
[ENH] Change AA config for Entangle

### ISSUE THREAD

**Issue by Vogliadicone** [brunocalado/savage-pathfinder-enhanced#4]
Not a real issue, but in the beginning Savage Pathfinder Enhanced used as the AA for entangle a "vines" / "entangle" effect.

After using your macro for Automated Animations again, the new version of Savage Pathfinder Enhanced set the AA for entangle like this:
![Entangle_1](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/119852651/856928fa-1b41-446d-b639-d556f2ea9003)
![Entangle_2](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/119852651/b298816a-ae50-497c-8e83-b2b1182a88dc)

Since I prefered the old AA, I tried to get it back and set the AA to (might not be your original solution, but that's the best solution I found):
![Entangle_3](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/119852651/092d3291-9880-4ee5-86cd-11b8d3b85f50)

Like I said, it's not a real issue, but if other users prefer the vines as well, maybe change the AA for entangle again.

- Foundry VTT: 11.305
- Swade System: 3.0.4
- Savage Pathfinder - Enhanced 0.6.2
- Automated Animations 4.2.60 (I configured AA to show the animation in general with the SWADE action roll)
- Sequencer 3.0.11
- SWADE Tools: 1.13.4
- Browser: Google Chrome

**Comment by brunocalado** [comment]
Don't you like vines better?
![image](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/4999783/a7fdbf25-6a85-4aa3-a47a-4d55d386509b)

**Comment by Vogliadicone** [comment]
I tested them as well, but found the "Entangle" AA a little bit nicer. But that might also be because I remember that one of my players used Entangle a lot and at that time it was set up with the "Entangle" AA. And since my players liked that a lot, I set that up again.
