### ISSUE TITLE
Both the Enchantments and Masterwork Forge Macros not working.

### ISSUE THREAD

**Issue by Deadlander** [brunocalado/savage-pathfinder-enhanced#5]
While trying to use the macros listed, both return the following error:
![image](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/13036735/724185d5-6fc6-4987-a0ab-43565665f344)
The Scroll-making macro works as intended.

Foundry v11.305
SWADE v3.0.5
Savage Pathfinder Enhanced v0.6.2

**Comment by brunocalado** [comment]
> While trying to use the macros listed, both return the following error: ![image](https://user-images.githubusercontent.com/13036735/253804102-724185d5-6fc6-4987-a0ab-43565665f344.png) The Scroll-making macro works as intended.
> 
> Foundry v11.305 SWADE v3.0.5 Savage Pathfinder Enhanced v0.6.2

update
it should be fixed

**Comment by Deadlander** [comment]
This error has returned with the update to the PFSW Core update.

**Comment by brunocalado** [comment]
fixed
