### ISSUE TITLE
[ENH] New crush damage rules

### ISSUE THREAD

**Issue by Vogliadicone** [brunocalado/savage-pathfinder-enhanced#6]
The new errata 5.0 for Savage Worlds:
https://peg-swade.s3.us-west-2.amazonaws.com/SWADE_Updates_v10.pdf
changed the way, crushed damage is handled:
"P101 GRAPPLING [4.0]: Replace the rules for Crush with the following:
Crush: As an action, a grappler may make a Strength roll as damage against a target he has Entangled or Bound. (This is a damage roll so Scale modifiers are ignored.)"

Even if there's no errata for Savage Pathfinder that changed the rules accordingly, I would recommend changing the grappling action in Savage Pathfinder Enhanced to the new implementation:
![Grapple_1](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/119852651/f066f18b-2c8c-4e10-89fe-ec41129acf4a)
![Grapple_2](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/119852651/2124840a-0a25-4273-865b-20bd8ac620b6)

- Foundry VTT: 11.307
- Swade System: 3.0.6
- Savage Pathfinder Enhanced 0.6.8
- Browser: Google Chrome

**Comment by brunocalado** [comment]
> This is for SWADE. Does it changed to SWPF?

**Comment by brunocalado** [comment]
done
