### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by DromedaryKing** [brunocalado/savage-pathfinder-enhanced#7]
If you try to install this module, it will point to a dependency called Warpgate (which should be here: [https://github.com/trioderegion/warpgate/](https://github.com/trioderegion/warpgate/)), however Warpgate currently doesn't exist, so the dependency can't be installed.

![image](https://github.com/brunocalado/savage-pathfinder-enhanced/assets/68353667/682029f8-1cff-439e-8011-35f43c7eaaf7)

**Comment by brunocalado** [comment]
oh no...

I'll take a look when swade v12 is out

**Comment by thinkedem** [comment]
> I'll take a look when swade v12 is out

Hi! Is there any update on this one? (Even if it's just that you didn't have time to look into it yet...)

**Comment by brunocalado** [comment]
> > I'll take a look when swade v12 is out
> 
> Hi! Is there any update on this one? (Even if it's just that you didn't have time to look into it yet...)

I think I fixed. Have you tried to update?

**Comment by thinkedem** [comment]
Ah I presume it is a v12 only update then. (Latest available version is for v11). Haven't fully jumped that gun yet since there are still some incompatible modules I use.

**Comment by brunocalado** [comment]
> Ah I presume it is a v12 only update then. (Latest available version is for v11). Haven't fully jumped that gun yet since there are still some incompatible modules I use.

Warpgame was removed from git, It can't be used anymore

**Comment by DromedaryKing** [comment]
Works fine for me now.

Thanks for the fix.
